import Head from 'next/head'
import ProtectedContent from '@/components/util/ProtectedContent'
import PageLayout from '@/components/util/PageLayout'

import { useRouter } from 'next/router'

export default function Images() {
  
    const router = useRouter()

    const {query} = router

    return (
    <>
      <Head>
        <title>{query.project} Images</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <ProtectedContent
          debug
          
        >
          <PageLayout>
            {/* <Sidebar/> */}
            <h1 className='text-center mt-4'>{query.project} Images</h1>
          </PageLayout>
        </ProtectedContent>
      </main>
    </>
  )
}
