import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import ProtectedContent from '@/components/util/ProtectedContent'
import SignIn from '@/components/util/SignIn'
import PageLayout from '@/components/util/PageLayout'
import { getProviders } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ providers }) {
  return (
    <>
      <Head>
        <title>Automate your QA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProtectedContent
          debug
          alt = {
              <SignIn providers = {providers}/>
          }
        >
            <h1 className='text-center mt-4'>Home</h1>
        </ProtectedContent>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const providers = await getProviders()
  return {
    props: { providers },
  }
}