import Head from 'next/head'
import ProtectedContent from '@/components/util/ProtectedContent'
import SignIn from '@/components/util/SignIn'
import PageLayout from '@/components/util/PageLayout'
import { getProviders } from 'next-auth/react'
import Sidebar from '@/components/sidebar/Sidebar'


export default function Account() {
  return (
    <>
      <Head>
        <title>AYQA Settings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProtectedContent
          debug
          
        >
            {/* <Sidebar/> */}
            <h1 className='text-center mt-4'>Settings</h1>
        </ProtectedContent>
      </main>
    </>
  )
}
